language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install: 
  - export TZ=Pacific/Noumea
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
install: "mvn clean install --settings target/travis/settings.xml"
env:
  global:
    - secure: "ozL2yswIRX5FJRhT3qbMlL23SzpFlJnPRKL3nMk6o5+5iPxG1Mk8e8VcCWWQHRLGtlRXywY3sJtIj4wENI3PSMCUo9Ho5gTlTPwAjdtz4NWpVib9Q180OihPjMkPJCH/8jOtUdiaOoCvCp8uiJWQcVIwx8PUqulvPeO+LN3NIyr2ElIY7OsEb2ELBn5UHPku6vra/SEW+LKr6IoN8nVSQV7OakDTUJLslKtM2emQkXpsNzQ9I3Qy2lin4EQ+qt/i9JXYZRNMYjRH0fAr3j6qvG4uil/xZM6YMPOVFcohEov75Q2xuIxk4TJm/Z83AmD8yalTJ6pilxDBeh/3diMex/motXZsASTMUVUhCKUJYxn9/BMUQiMND5wznfBZOWhb7ZBIYUgJUNZkPZ0gKnxbNG2gOIwgLh65bv3f7mWK6Mfgo7dfgHq3fYJJuMBUgE2vJTf/rzAFM7rN42/raqYzRDndsZ1E8XYutapDp8JSQxm4O/CMHp2x+7lQVfTjRen6ircrwMuw+32fpvk9cAWwJ9IShQ1wsUo6wTxYxFTqthWkvF5KPFGS5PuclbPQqeUbezGOAiFV6OWpEaKxBvJegGJ60jxFhl9Pi+ueHkTGlSCk3zZ+5SmogiG2WsaV/VmW+OetnrOTXl5R3/kzFZ5t9nRoG82T6/Spza+aQsyelDU="
    - secure: "N10nZfjPZalUB1xXIhoVN0MPgj2ywtA1LG5nljeP5fvOOPkN3TTsfsOqR9hW3V/ywuwqN6IXjwlQVqDBKkwoms8fMY99CxwVKhozf6vSkmaKpI0eMREKzvcx4pVO/zecd6GpyKXdWr5/17+FIsIuRMx2fyaAHFbE8tMtDX0FZ4J0PW2dZ4LqfvALYHqENEZ+fIPyuk5H148EMgSJ97cAMdgmaEZAJS9QUyPjBtIJIJVhkFH6asnldYnXEjNl/OtFSpiSaNFr1PIc90QDU5B8jADqHDbChJsoZ8ZJUtxmtnvqB7TTfwIO3mTeDTWdYkwoXJ7aVD/mmOL1I4AyqepA09pznan46hALa87bopplHf9jDT3Uvkzkv4Il5Howr5QjYbkFLIe6iy91JUyNebQGno58W5fjSVrwuLZbqpCJpIQIazHAo2s+mcqaXBDZwEwewx5DTGonGF+DcayldYDJYnmrO8vY6MlwbsMc3+VgQXj9zwbPGC8fASvCujaytThy0BCYqVARfS8mKGoCuVwHHzVdaMlWtzdlHIHkyMI5xuqngArqj6f5MIKNKdwm1vF8Q0Y4OBiUOsP4YaiWbW41rOnNu/Lht1zCXsjzoOmYsDmAPf8uZr4cpruh3qAxKDvx4pAiBUFaWQMh1OWDtQ9jrZzj42igr0SLawth2iBJkuk=" 
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report    

